name: Weekly Notebook Test

on:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at midnight UTC
  workflow_dispatch: # Run on Click too

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install numpy 
          pip install classiq 
          pip install scipy 
          pip install matplotlib 
          pip install IPython 
          pip install pandas 
          pip install sympy

      - name: Install Jupyter
        run: |
          pip install jupyter 
          pip install jupyterlab
          pip install --upgrade pip ipython ipykernel
          ipython kernel install --name "py38_classiq_secondary" --user # Because of some kernel bug
          ipython kernel install --name "py38_classiq" --user # Because of some kernel bug

      - name: Run Jupyter Notebooks
        run: |
          jupyter nbconvert --to notebook --execute RainbowOptions-DirectMethod.ipynb
          jupyter nbconvert --to notebook --execute RainbowOptions-IntegrationMethod.ipynb

      # Add more steps for testing as needed
